-- Clear existing data if needed (Optional)
-- SET FOREIGN_KEY_CHECKS = 0;
-- TRUNCATE TABLE course_skills;
-- TRUNCATE TABLE courses;
-- TRUNCATE TABLE skills;
-- SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------------------
-- 1. Insert Skills
-- ---------------------------------------------------------
INSERT INTO skills (name, description) VALUES
('Artificial Neural Network', 'Skill related to various courses'),
('Autoscaling', 'Skill related to various courses'),
('Backpropagation', 'Skill related to various courses'),
('Basic Programming Language', 'Skill related to various courses'),
('Binary Code', 'Skill related to various courses'),
('Cloud Computing', 'Skill related to various courses'),
('Cloud Databases', 'Skill related to various courses'),
('Cloud Storage', 'Skill related to various courses'),
('Command-Line Interface', 'Skill related to various courses'),
('Computer Programming', 'Skill related to various courses'),
('Convolutional Neural Network', 'Skill related to various courses'),
('Customer Support', 'Skill related to various courses'),
('Data Analysis', 'Skill related to various courses'),
('Data Science', 'Skill related to various courses'),
('Data Store', 'Skill related to various courses'),
('Data Structure', 'Skill related to various courses'),
('Data Virtualization', 'Skill related to various courses'),
('Data Visualization (DataViz)', 'Skill related to various courses'),
('Database (DBMS)', 'Skill related to various courses'),
('Debugging', 'Skill related to various courses'),
('Deep Learning', 'Skill related to various courses'),
('Directory Service', 'Skill related to various courses'),
('Domain Name System (DNS)', 'Skill related to various courses'),
('Facial Recognition System', 'Skill related to various courses'),
('Google App Engine (GAE)', 'Skill related to various courses'),
('Google Cloud Platform', 'Skill related to various courses'),
('Google Compute Engine', 'Skill related to various courses'),
('Gratitude', 'Skill related to various courses'),
('Happiness', 'Skill related to various courses'),
('Hyperparameter', 'Skill related to various courses'),
('Hyperparameter Optimization', 'Skill related to various courses'),
('Inductive Transfer', 'Skill related to various courses'),
('Ipv4', 'Skill related to various courses'),
('Ipython', 'Skill related to various courses'),
('Json', 'Skill related to various courses'),
('Lightweight Directory Access Protocol (LDAP)', 'Skill related to various courses'),
('Linux', 'Skill related to various courses'),
('Linux File Systems', 'Skill related to various courses'),
('Load Balancing', 'Skill related to various courses'),
('Logistic Regression', 'Skill related to various courses'),
('Machine Learning', 'Skill related to various courses'),
('Machine Learning (ML) Algorithms', 'Skill related to various courses'),
('Matplotlib', 'Skill related to various courses'),
('Meditation', 'Skill related to various courses'),
('Model Selection', 'Skill related to various courses'),
('Multi-Task Learning', 'Skill related to various courses'),
('Network Architecture', 'Skill related to various courses'),
('Network Model', 'Skill related to various courses'),
('Numpy', 'Skill related to various courses'),
('Pandas', 'Skill related to various courses'),
('Powershell', 'Skill related to various courses'),
('Predictive Modelling', 'Skill related to various courses'),
('Python Programming', 'Skill related to various courses'),
('Python Syntax And Semantics', 'Skill related to various courses'),
('Relational Database Management System (RDBMS)', 'Skill related to various courses'),
('Rstudio', 'Skill related to various courses'),
('SQL', 'Skill related to various courses'),
('Savoring', 'Skill related to various courses'),
('Sqlite', 'Skill related to various courses'),
('Tensorflow', 'Skill related to various courses'),
('Troubleshooting', 'Skill related to various courses'),
('Tuple', 'Skill related to various courses'),
('Virtual Machine', 'Skill related to various courses'),
('Virtual Private Network (VPN)', 'Skill related to various courses'),
('Web Scraping', 'Skill related to various courses'),
('Xml', 'Skill related to various courses') ON DUPLICATE KEY UPDATE name=name;

-- ---------------------------------------------------------
-- 2. Insert Courses
-- ---------------------------------------------------------
INSERT INTO courses (title, description, category, course_url) VALUES
('IBM Data Science', 'Data Science has been ranked as one of the hottest professions and the demand for data practitioners is booming. This Professional Certificate from IBM is intended for anyone interested in developing skills and experience to pursue a career in Data Science or Machine Learning.

This program consists of 9 courses providing you with latest job-ready skills and techniques covering a wide array of dat...', 'Beginner', 'https://www.coursera.org/professional-certificates/ibm-data-science'),
('Introduction to Data Science', 'In this Specialization learners will develop foundational Data Science skills to prepare them for a career or further learning that involves more advanced topics in Data Science. The specialization entails understanding what is Data Science and the various kinds of activities that a Data Scientist performs. It will familiarize learners with various open source tools, like Jupyter notebooks, used b...', 'Beginner', 'https://www.coursera.org/specializations/introduction-data-science'),
('Python for Everybody', 'This Specialization builds on the success of the Python for Everybody course and will introduce fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language. In the Capstone Project, you’ll use the technologies learned throughout the Specialization to design and create your own applications for data retri...', 'Beginner', 'https://www.coursera.org/specializations/python'),
('Google IT Support', 'This 5-course certificate, developed by Google, includes innovative curriculum designed to prepare you for an entry-level role in IT support. A job in IT can mean in-person or remote help desk work in a small business or at a global company like Google. The program is part of Grow with Google, a Google initiative to help create economic opportunities for all Americans. Learn more.

Upon completion...', 'Beginner', 'https://www.coursera.org/professional-certificates/google-it-support'),
('Deep Learning', 'If you want to break into AI, this Specialization will help you do so. Deep Learning is one of the most highly sought after skills in tech. We will help you become good at Deep Learning.

In five courses, you will learn the foundations of Deep Learning, understand how to build neural networks, and learn how to lead successful machine learning projects. You will learn about Convolutional networks, ...', 'Beginner', 'https://www.coursera.org/specializations/deep-learning'),
('The Science of Well-Being', 'In this course you will engage in a series of challenges designed to increase your own happiness and build more productive habits. As preparation for these tasks, Professor Laurie Santos reveals misconceptions about happiness, annoying features of the mind that lead us to think the way we do, and the research that can help us change. You will ultimately be prepared to successfully incorporate a sp...', 'Beginner', 'https://www.coursera.org/learn/the-science-of-well-being'),
('Machine Learning', 'Machine learning is the science of getting computers to act without being explicitly programmed. In the past decade, machine learning has given us self-driving cars, practical speech recognition, effective web search, and a vastly improved understanding of the human genome. Machine learning is so pervasive today that you probably use it dozens of times a day without knowing it. Many researchers al...', 'Beginner', 'https://www.coursera.org/learn/machine-learning'),
('Applied Data Science', 'This is an action-packed specialization is for data science enthusiasts who want to acquire practical skills for real world data problems. It appeals to anyone interested in pursuing a career in Data Science, and already has foundational skills (or has completed the Introduction to Applied Data Science specialization). You will learn Python - no prior programming knowledge necessary. You will then...', 'Beginner', 'https://www.coursera.org/specializations/applied-data-science'),
('Cloud Architecture with Google Cloud', 'The Google Cloud Professional Cloud Architect certification was ranked one of the top paying IT certifications of 2019 by Global Knowledge.

This program provides the skills you need to advance your career as a professional cloud architect and recommends training to support your preparation for the industry-recognized Google Cloud Professional Cloud Architect certification.

You''''ll have the oppor...', 'Beginner', 'https://www.coursera.org/professional-certificates/gcp-cloud-architect'),
('Cloud Engineering with Google Cloud', 'This program provides the skills you need to advance your career as a cloud engineer and recommends training to support your preparation for the industry-recognized Google Cloud Associate Cloud Engineer.

You''''ll also have the opportunity to practice key job skills, such as setting up a cloud environment and configuring and deploying a solution in the cloud.

Upon successful completion of this pro...', 'Beginner', 'https://www.coursera.org/professional-certificates/cloud-engineering-gcp');

-- ---------------------------------------------------------
-- 3. Insert Course-Skill Mappings
-- ---------------------------------------------------------
INSERT INTO course_skills (course_id, skill_id, weight) VALUES
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Science' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Machine Learning' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Analysis' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Visualization (DataViz)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Numpy' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Pandas' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Databases' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Ipython' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Relational Database Management System (RDBMS)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'SQL' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'IBM Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Predictive Modelling' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Science' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Rstudio' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'SQL' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Databases' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Ipython' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Introduction to Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Relational Database Management System (RDBMS)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Json' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Xml' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Database (DBMS)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Syntax And Semantics' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Basic Programming Language' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Computer Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Structure' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Tuple' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Web Scraping' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'Sqlite' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Python for Everybody' LIMIT 1), (SELECT id FROM skills WHERE name = 'SQL' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Binary Code' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Customer Support' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Linux' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Troubleshooting' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Domain Name System (DNS)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Ipv4' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Network Model' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Powershell' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Linux File Systems' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Command-Line Interface' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Directory Service' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Google IT Support' LIMIT 1), (SELECT id FROM skills WHERE name = 'Lightweight Directory Access Protocol (LDAP)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Tensorflow' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Convolutional Neural Network' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Artificial Neural Network' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Deep Learning' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Backpropagation' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Hyperparameter' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Hyperparameter Optimization' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Machine Learning' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Inductive Transfer' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Multi-Task Learning' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Deep Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Facial Recognition System' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'The Science of Well-Being' LIMIT 1), (SELECT id FROM skills WHERE name = 'Gratitude' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'The Science of Well-Being' LIMIT 1), (SELECT id FROM skills WHERE name = 'Happiness' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'The Science of Well-Being' LIMIT 1), (SELECT id FROM skills WHERE name = 'Meditation' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'The Science of Well-Being' LIMIT 1), (SELECT id FROM skills WHERE name = 'Savoring' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Machine Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Logistic Regression' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Machine Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Artificial Neural Network' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Machine Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Machine Learning (ML) Algorithms' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Machine Learning' LIMIT 1), (SELECT id FROM skills WHERE name = 'Machine Learning' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Analysis' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Python Programming' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Visualization (DataViz)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Matplotlib' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Science' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Numpy' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Pandas' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Predictive Modelling' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Model Selection' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Applied Data Science' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Virtualization' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google Compute Engine' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google App Engine (GAE)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google Cloud Platform' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Computing' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Virtual Machine' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Network Architecture' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Debugging' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Storage' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Store' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Load Balancing' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Virtual Private Network (VPN)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Architecture with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Autoscaling' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google Compute Engine' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google App Engine (GAE)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Google Cloud Platform' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Computing' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Virtual Machine' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Network Architecture' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Debugging' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Cloud Storage' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Data Store' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Load Balancing' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Virtual Private Network (VPN)' LIMIT 1), 1.0),
((SELECT id FROM courses WHERE title = 'Cloud Engineering with Google Cloud' LIMIT 1), (SELECT id FROM skills WHERE name = 'Autoscaling' LIMIT 1), 1.0);
